### ISSUE TITLE
Problems with Kappa after update

### ISSUE THREAD

**Issue by myavitt** [fiji/Kappa#6]
Hello,

I used Kappa maybe ~6 months ago and it worked great. However, I recently updated Fiji and was unable to find Kappa in the Plugins --> Analyze menu. When I follow the instructions to install in the README file (Update --> Manage update sites), Kappa is checked, but does still not show up. Do you have any advice to troubleshoot this problem?

Thanks.

**Comment by amartin7211** [comment]
I am also having this problem

**Comment by Batir1988** [comment]
Me too....not able to find it even after reinstalling Fiji

**Comment by hadim** [comment]
Indeed I don't know what happened during the last automatic update. I just tried to upload manually the 2.0.0 version using https://imagej.net/How_to_set_up_and_populate_an_update_site but ImageJ does not let me upload the Kappa jar file. In the details I can read `This file is no longer needed`.

@ctrueden do you have an idea? I guess something went wrong with the update site and I don't think I can fix it myself.

**Comment by hadim** [comment]
Maven repo has also not been updated for a while now: https://maven.scijava.org/#nexus-search;quick~kappa

**Comment by hadim** [comment]
@Batir1988 @amartin7211 sorry again for the trouble, here is a link to the JAR file: https://drive.google.com/file/d/1W9ncjzNr8HVk6lcFbiomBTzClQrZ-ttJ/view?usp=sharing

The file is called `Kappa-2.0.0.jar` after adding it to `Fiji.app/jars` you can restart Fiji and then it should work as excepted.

Also, next time you have such an issue you should report it on the forum instead of Github, you'll get a faster answer there: https://forum.image.sc/

**Comment by imagejan** [comment]
Indeed, `Kappa-2.0.0` failed to be deployed to the maven repository, because apparently the required environment variables are missing since the move to the `fiji` org.

See the [build log](https://travis-ci.com/github/fiji/Kappa/builds/182335440#L216-L217):

```
== Configuring Maven ==

No deploy -- secure environment variables not available
```

That should be independent of the update site though.

**Comment by hadim** [comment]
> I figured that this might be intended, as Kappa is supposed to be included in Fiji now, so shipping via the _Java-8_ update site instead of its own update site. Something might have gone wrong with uploading it to the _Java-8_ update site, though...

I haven't realized that was going to be integrated into Fiji directly. This is great news!

**Comment by imagejan** [comment]
Well, that was just a guess, seeing the commit message of that recent commit by @ctrueden: https://github.com/fiji/Kappa/commit/cfe7cd0e6a534944ab8261f56f13cd3f98102f10

I guess what's needed to finalize integration into Fiji is an update to the `pom.xml` in `fiji/fiji`.

---

Until then, I fixed the maven deployment by re-running `travisify.sh` on this repository, so that `sc.fiji:Kappa` is now correctly deployed to `maven.scijava.org`:

https://maven.scijava.org/#nexus-search;gav~sc.fiji~Kappa~~~

**Comment by hadim** [comment]
Thank you @imagejan for doing this.

@Batir1988 @amartin7211 : you can now use the following link https://maven.scijava.org/service/local/artifact/maven/redirect?r=snapshots&g=sc.fiji&a=Kappa&v=2.0.1-SNAPSHOT&e=jar

**Comment by imagejan** [comment]
`Kappa-2.0.0.jar` is now part of Fiji (no need to activate an extra update site), so I'm closing this issue.
