### ISSUE TITLE
Cannot run Kappa on Fiji

### ISSUE THREAD

**Issue by beapravia** [fiji/Kappa#7]
Hello,

I've installed Kappa as indicated in here https://github.com/brouhardlab/Kappa/tree/master/docs and even though it does appear in my updates, it is not in 'Analyze' (nor anywhere else I can see), hence I cannot run the plugin.

Thanks in advance for your help!

**Comment by imagejan** [comment]
Indeed, the Kappa update site stopped shipping the plugin because it is going to be included into core Fiji. However, that transition is not yet completed, see also https://github.com/fiji/Kappa/issues/6.

In the meantime, please download `Kappa-2.0.1-SNAPSHOT.jar` [here](https://maven.scijava.org/service/local/repositories/snapshots/content/sc/fiji/Kappa/2.0.1-SNAPSHOT/Kappa-2.0.1-20200915.145808-1.jar) and put it into your `Fiji.app/jars` folder.

**Comment by beapravia** [comment]
Sorry I hadn't seen that issue before!

It worked. Thanks a lot!

**Comment by imagejan** [comment]
`Kappa-2.0.0.jar` is now part of Fiji (no need to activate an extra update site), so I'm closing this issue.
